[pipeline]
output_dir = "repository"
cache_dir = ".cache"

[knowledge_graph]
# Enable or disable the association of descriptive text with graph nodes
associate_descriptions = true

technical_entities = ["CLASS", "FUNCTION"]
enabled_spacy_entities = ["ORG", "PRODUCT"]

# Define each documentation target you want to process
[targets.firecrawl]
url = "https://docs.firecrawl.dev/"
page_limit = 500

[targets.langchain]
url = "https://python.langchain.com/docs/get_started/introduction"
page_limit = 2000