# =================================================================
# Automated Knowledge Pack Builder Configuration (Vector Search MVP)
# =================================================================

[pipeline]
# Directory where the final Knowledge Packs will be saved.
output_dir = "repository"
# Directory for caching raw scraped data to avoid re-scraping.
cache_dir = ".cache"

[vector_store]
# The sentence-transformer model to use for creating embeddings.
# 'all-MiniLM-L6-v2' is a great, lightweight default.
embedding_model_name = "all-MiniLM-L6-v2"

# =================================================================
# Target Definitions
# Each target represents a documentation website to be processed.
# For the vector search MVP, only the URL and page limit are needed.
# =================================================================

[targets.langchain]
url = "https://python.langchain.com/docs/get_started/introduction"
page_limit = 2000

[targets.mintlify]
url = "https://mintlify.com/docs"
page_limit = 500

[targets.firecrawl]
url = "https://docs.firecrawl.dev/"
page_limit = 500

[targets.pydanticai]
url = "https://ai.pydantic.dev/"
page_limit = 5