# docker-compose.yml
# version: '3.8'

services:
  knowledge-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount the local 'repository' dir into the container's 'packs' dir
      - ./repository:/packs
      # Mount a volume for the internal cache to persist it across restarts
      - api_data:/data
    environment:
      # Configure the API to run in local mode
      - STORAGE_PROVIDER=local
      # Tell the LocalStorageProvider where to find the packs inside the container
      - LOCAL_PACKS_PATH=/packs

volumes:
  api_data:
