
services:
  knowledge-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./repository:/packs
      - api_data:/data
    env_file:
      - .env
    environment:
      STORAGE_PROVIDER: ${STORAGE_PROVIDER}
      LOCAL_PACKS_PATH: ${LOCAL_PACKS_PATH}

volumes:
  api_data:
